# foundry.toml - v1.0

[profile.default]
fs_permissions = [{ access = "read-write", path = "./" }]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"

# Remappings pour imports
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink-brownie-contracts/"
]

# Optimizations
optimizer = true
optimizer_runs = 200

# Tests config
verbosity = 2
fuzz_runs = 256

# Gas reports
gas_reports = ["LendingPoolV2", "HealthCalculator"]
